#!/bin/bash

git add .

git commit -m "Don't just count your directories, make your directories count"

git update-index --chmod=+x 11-directories

git add .

git commit -m "Don't just count your directories, make your directories count"

git push