#!/bin/bash

git add .

git commit -m "It is a good file that cuts iron without making a noise"

git update-index --chmod=+x 7-file

git add .

git commit -m "It is a good file that cuts iron without making a noise"

git push