#!/bin/bash

git add .

git commit -m "Being unique is better than being perfect"

git update-index --chmod=+x 13-unique

git add .

git commit -m "Being unique is better than being perfect"

git push