#!/bin/bash

git add .

git commit -m "If the path be beautiful, let us not ask where it leads"

git update-index --chmod=+x 3-paths

git add .

git commit -m "If the path be beautiful, let us not ask where it leads"

git push