#!/bin/bash

git add .

git commit -m "The eggs of the brood need to be an odd number"

git update-index --chmod=+x 102-odd

git add .

git commit -m "The eggs of the brood need to be an odd number"

git push
